### ISSUE TITLE
alter list of toolchain modules included in the report

### ISSUE THREAD

**Issue by karenetheridge** [cpan-testers/CPAN-Testers-Common-Client#10]
looking at a recent report, http://www.cpantesters.org/cpan/report/35da0d0c-0972-11e6-ba1f-cf8008213c65 --

I see the versions are reported for JSON and JSON::PP -- but JSON.pm is not a toolchain module.  Instead the report should mention Parse::CPAN::Meta and the values of the json backend environment variables (note that the number of these variables is growing in @shadowcat-mst's upcoming changes there)

**Comment by karenetheridge** [comment]
I will think more about what modules should be added.

**Comment by karenetheridge** [comment]
Definitely include the values of these environment variables, and then the corresponding installed versions of their *values*:

 * PERL_YAML_BACKEND
 * CPAN_META_JSON_DECODER
 * CPAN_META_JSON_BACKEND
 * PERL_JSON_BACKEND

**Comment by karenetheridge** [comment]
I recall us discussing this at last year's hackathon in Lyon -- is the list also in a different module than this one?

**Comment by garu** [comment]
It's not, but not all clients have been properly migrated to the common::client :X 

Anyway, fixed! /PERL/ env vars were already been added, but now I look for /CPAN_META/ as well.
